import { defineType } from 'sanity'

export const realisation = defineType({
  name: 'realisation',
  title: 'Réalisation',
  type: 'document',
  groups: [
    { name: 'preview', title: 'Preview (carte page Réalisations)', default: true },
    { name: 'hero', title: 'Hero (page détail)' },
    { name: 'meta', title: 'Méta-données projet' },
    { name: 'intro', title: 'Introduction (Le Projet)' },
    { name: 'approach', title: 'Défi & Solution (Notre Approche)' },
    { name: 'features', title: 'Points Forts' },
    { name: 'gallery', title: 'Galerie' },
    { name: 'results', title: 'Résultats & Témoignage' },
  ],
  fields: [
    {
      name: 'slug',
      title: 'Slug (URL)',
      type: 'slug',
      options: { source: 'previewTitle_fr', maxLength: 96 },
      group: 'preview',
    },
    // ——— Preview (carte sur la page Réalisations) ———
    {
      name: 'previewImage',
      title: 'Photo preview',
      type: 'image',
      group: 'preview',
    },
    {
      name: 'previewCategory_fr',
      title: 'Catégorie preview (FR)',
      type: 'string',
      description: 'Ex: Création Sur-Mesure • 2022',
      group: 'preview',
    },
    {
      name: 'previewCategory_en',
      title: 'Catégorie preview (EN)',
      type: 'string',
      group: 'preview',
    },
    {
      name: 'previewTitle_fr',
      title: 'Titre preview (FR)',
      type: 'string',
      description: 'Ex: Villa Privée',
      group: 'preview',
    },
    {
      name: 'previewTitle_en',
      title: 'Titre preview (EN)',
      type: 'string',
      group: 'preview',
    },
    {
      name: 'previewLieu_fr',
      title: 'Lieu preview (FR)',
      type: 'string',
      description: 'Ex: Vandœuvres, Suisse',
      group: 'preview',
    },
    {
      name: 'previewLieu_en',
      title: 'Lieu preview (EN)',
      type: 'string',
      group: 'preview',
    },
    {
      name: 'previewDescription_fr',
      title: 'Description principale preview (FR)',
      type: 'text',
      group: 'preview',
    },
    {
      name: 'previewDescription_en',
      title: 'Description principale preview (EN)',
      type: 'text',
      group: 'preview',
    },
    // ——— Hero (page détail) ———
    {
      name: 'heroImage',
      title: 'Image hero',
      type: 'image',
      group: 'hero',
    },
    {
      name: 'heroBadge_fr',
      title: 'Badge hero (FR)',
      type: 'string',
      description: 'Ex: Résidentiel de Prestige',
      group: 'hero',
    },
    {
      name: 'heroBadge_en',
      title: 'Badge hero (EN)',
      type: 'string',
      group: 'hero',
    },
    {
      name: 'heroTitle_fr',
      title: 'Titre hero (FR)',
      type: 'string',
      description: 'Ex: Villa Privée',
      group: 'hero',
    },
    {
      name: 'heroTitle_en',
      title: 'Titre hero (EN)',
      type: 'string',
      group: 'hero',
    },
    {
      name: 'heroTitleSuffix_fr',
      title: 'Suffixe titre hero (FR)',
      type: 'string',
      description: 'Ex: Vandœuvres (sous le titre)',
      group: 'hero',
    },
    {
      name: 'heroTitleSuffix_en',
      title: 'Suffixe titre hero (EN)',
      type: 'string',
      group: 'hero',
    },
    {
      name: 'heroSubtitle_fr',
      title: 'Sous-titre hero (FR)',
      type: 'text',
      group: 'hero',
    },
    {
      name: 'heroSubtitle_en',
      title: 'Sous-titre hero (EN)',
      type: 'text',
      group: 'hero',
    },
    // ——— Méta-données ———
    {
      name: 'metaTypeLabel_fr',
      title: 'Label Type (FR)',
      type: 'string',
      description: 'Ex: Type',
      group: 'meta',
    },
    {
      name: 'metaTypeLabel_en',
      title: 'Label Type (EN)',
      type: 'string',
      group: 'meta',
    },
    {
      name: 'metaTypeValue_fr',
      title: 'Valeur Type (FR)',
      type: 'string',
      description: 'Ex: Résidentiel Privé',
      group: 'meta',
    },
    {
      name: 'metaTypeValue_en',
      title: 'Valeur Type (EN)',
      type: 'string',
      group: 'meta',
    },
    {
      name: 'metaYear',
      title: 'Année',
      type: 'number',
      group: 'meta',
    },
    {
      name: 'metaLocationLabel_fr',
      title: 'Label Localisation (FR)',
      type: 'string',
      group: 'meta',
    },
    {
      name: 'metaLocationLabel_en',
      title: 'Label Localisation (EN)',
      type: 'string',
      group: 'meta',
    },
    {
      name: 'metaLocationValue_fr',
      title: 'Valeur Localisation (FR)',
      type: 'string',
      description: 'Ex: Vandœuvres, Suisse',
      group: 'meta',
    },
    {
      name: 'metaLocationValue_en',
      title: 'Valeur Localisation (EN)',
      type: 'string',
      group: 'meta',
    },
    {
      name: 'metaFourthLabel_fr',
      title: 'Label 4e méta (FR)',
      type: 'string',
      description: 'Ex: Durée ou Surface',
      group: 'meta',
    },
    {
      name: 'metaFourthLabel_en',
      title: 'Label 4e méta (EN)',
      type: 'string',
      group: 'meta',
    },
    {
      name: 'metaFourthValue_fr',
      title: 'Valeur 4e méta (FR)',
      type: 'string',
      description: 'Ex: 4 mois ou 450 m²',
      group: 'meta',
    },
    {
      name: 'metaFourthValue_en',
      title: 'Valeur 4e méta (EN)',
      type: 'string',
      group: 'meta',
    },
    // ——— Introduction (Le Projet) ———
    {
      name: 'introLabel_fr',
      title: 'Label section intro (FR)',
      type: 'string',
      description: 'Ex: Le Projet',
      group: 'intro',
    },
    {
      name: 'introLabel_en',
      title: 'Label section intro (EN)',
      type: 'string',
      group: 'intro',
    },
    {
      name: 'introTitle_fr',
      title: 'Titre intro (FR)',
      type: 'string',
      group: 'intro',
    },
    {
      name: 'introTitle_en',
      title: 'Titre intro (EN)',
      type: 'string',
      group: 'intro',
    },
    {
      name: 'introLead_fr',
      title: 'Chapô intro (FR)',
      type: 'text',
      group: 'intro',
    },
    {
      name: 'introLead_en',
      title: 'Chapô intro (EN)',
      type: 'text',
      group: 'intro',
    },
    {
      name: 'introDescription_fr',
      title: 'Description intro (FR)',
      type: 'text',
      group: 'intro',
    },
    {
      name: 'introDescription_en',
      title: 'Description intro (EN)',
      type: 'text',
      group: 'intro',
    },
    // ——— Défi & Solution ———
    {
      name: 'approachSectionTitle_fr',
      title: 'Titre section Approche (FR)',
      type: 'string',
      description: 'Ex: Notre Approche',
      group: 'approach',
    },
    {
      name: 'approachSectionTitle_en',
      title: 'Titre section Approche (EN)',
      type: 'string',
      group: 'approach',
    },
    {
      name: 'challengeTitle_fr',
      title: 'Titre Défi (FR)',
      type: 'string',
      group: 'approach',
    },
    {
      name: 'challengeTitle_en',
      title: 'Titre Défi (EN)',
      type: 'string',
      group: 'approach',
    },
    {
      name: 'challengeDescription_fr',
      title: 'Description Défi (FR)',
      type: 'text',
      group: 'approach',
    },
    {
      name: 'challengeDescription_en',
      title: 'Description Défi (EN)',
      type: 'text',
      group: 'approach',
    },
    {
      name: 'solutionTitle_fr',
      title: 'Titre Solution (FR)',
      type: 'string',
      group: 'approach',
    },
    {
      name: 'solutionTitle_en',
      title: 'Titre Solution (EN)',
      type: 'string',
      group: 'approach',
    },
    {
      name: 'solutionDescription_fr',
      title: 'Description Solution (FR)',
      type: 'text',
      group: 'approach',
    },
    {
      name: 'solutionDescription_en',
      title: 'Description Solution (EN)',
      type: 'text',
      group: 'approach',
    },
    // ——— Points Forts (4 cartes) ———
    {
      name: 'featuresTitle_fr',
      title: 'Titre section Points Forts (FR)',
      type: 'string',
      group: 'features',
    },
    {
      name: 'featuresTitle_en',
      title: 'Titre section Points Forts (EN)',
      type: 'string',
      group: 'features',
    },
    {
      name: 'featuresSubtitle_fr',
      title: 'Sous-titre Points Forts (FR)',
      type: 'string',
      group: 'features',
    },
    {
      name: 'featuresSubtitle_en',
      title: 'Sous-titre Points Forts (EN)',
      type: 'string',
      group: 'features',
    },
    {
      name: 'feature1Title_fr',
      title: 'Point fort 1 - Titre (FR)',
      type: 'string',
      group: 'features',
    },
    {
      name: 'feature1Title_en',
      title: 'Point fort 1 - Titre (EN)',
      type: 'string',
      group: 'features',
    },
    {
      name: 'feature1Description_fr',
      title: 'Point fort 1 - Description (FR)',
      type: 'text',
      group: 'features',
    },
    {
      name: 'feature1Description_en',
      title: 'Point fort 1 - Description (EN)',
      type: 'text',
      group: 'features',
    },
    {
      name: 'feature2Title_fr',
      title: 'Point fort 2 - Titre (FR)',
      type: 'string',
      group: 'features',
    },
    {
      name: 'feature2Title_en',
      title: 'Point fort 2 - Titre (EN)',
      type: 'string',
      group: 'features',
    },
    {
      name: 'feature2Description_fr',
      title: 'Point fort 2 - Description (FR)',
      type: 'text',
      group: 'features',
    },
    {
      name: 'feature2Description_en',
      title: 'Point fort 2 - Description (EN)',
      type: 'text',
      group: 'features',
    },
    {
      name: 'feature3Title_fr',
      title: 'Point fort 3 - Titre (FR)',
      type: 'string',
      group: 'features',
    },
    {
      name: 'feature3Title_en',
      title: 'Point fort 3 - Titre (EN)',
      type: 'string',
      group: 'features',
    },
    {
      name: 'feature3Description_fr',
      title: 'Point fort 3 - Description (FR)',
      type: 'text',
      group: 'features',
    },
    {
      name: 'feature3Description_en',
      title: 'Point fort 3 - Description (EN)',
      type: 'text',
      group: 'features',
    },
    {
      name: 'feature4Title_fr',
      title: 'Point fort 4 - Titre (FR)',
      type: 'string',
      group: 'features',
    },
    {
      name: 'feature4Title_en',
      title: 'Point fort 4 - Titre (EN)',
      type: 'string',
      group: 'features',
    },
    {
      name: 'feature4Description_fr',
      title: 'Point fort 4 - Description (FR)',
      type: 'text',
      group: 'features',
    },
    {
      name: 'feature4Description_en',
      title: 'Point fort 4 - Description (EN)',
      type: 'text',
      group: 'features',
    },
    // ——— Galerie ———
    {
      name: 'galleryTitle_fr',
      title: 'Titre galerie (FR)',
      type: 'string',
      group: 'gallery',
    },
    {
      name: 'galleryTitle_en',
      title: 'Titre galerie (EN)',
      type: 'string',
      group: 'gallery',
    },
    {
      name: 'gallerySubtitle_fr',
      title: 'Sous-titre galerie (FR)',
      type: 'string',
      group: 'gallery',
    },
    {
      name: 'gallerySubtitle_en',
      title: 'Sous-titre galerie (EN)',
      type: 'string',
      group: 'gallery',
    },
    {
      name: 'galleryItems',
      title: 'Images galerie',
      type: 'array',
      of: [
        {
          type: 'object',
          fields: [
            { name: 'image', title: 'Image', type: 'image' },
            { name: 'caption_fr', title: 'Légende (FR)', type: 'string' },
            { name: 'caption_en', title: 'Légende (EN)', type: 'string' },
          ],
          preview: {
            select: { media: 'image', title: 'caption_fr' },
            prepare: ({ media, title }) => ({ media, title: title || 'Sans légende' }),
          },
        },
      ],
      group: 'gallery',
    },
    // ——— Résultats & Témoignage ———
    {
      name: 'quoteText_fr',
      title: 'Citation (FR)',
      type: 'text',
      group: 'results',
    },
    {
      name: 'quoteText_en',
      title: 'Citation (EN)',
      type: 'text',
      group: 'results',
    },
    {
      name: 'quoteAuthor_fr',
      title: 'Auteur citation (FR)',
      type: 'string',
      group: 'results',
    },
    {
      name: 'quoteAuthor_en',
      title: 'Auteur citation (EN)',
      type: 'string',
      group: 'results',
    },
    {
      name: 'quotePosition_fr',
      title: 'Fonction / lieu auteur (FR)',
      type: 'string',
      description: 'Ex: Villa à Vandœuvres',
      group: 'results',
    },
    {
      name: 'quotePosition_en',
      title: 'Fonction / lieu auteur (EN)',
      type: 'string',
      group: 'results',
    },
    {
      name: 'stat1Number',
      title: 'Stat 1 - Nombre',
      type: 'string',
      description: 'Ex: 85, 4, 100%',
      group: 'results',
    },
    {
      name: 'stat1Label_fr',
      title: 'Stat 1 - Label (FR)',
      type: 'string',
      group: 'results',
    },
    {
      name: 'stat1Label_en',
      title: 'Stat 1 - Label (EN)',
      type: 'string',
      group: 'results',
    },
    {
      name: 'stat2Number',
      title: 'Stat 2 - Nombre',
      type: 'string',
      group: 'results',
    },
    {
      name: 'stat2Label_fr',
      title: 'Stat 2 - Label (FR)',
      type: 'string',
      group: 'results',
    },
    {
      name: 'stat2Label_en',
      title: 'Stat 2 - Label (EN)',
      type: 'string',
      group: 'results',
    },
    {
      name: 'stat3Number',
      title: 'Stat 3 - Nombre',
      type: 'string',
      description: 'Ex: 18 pour 18e siècle',
      group: 'results',
    },
    {
      name: 'stat3Label_fr',
      title: 'Stat 3 - Label (FR)',
      type: 'string',
      group: 'results',
    },
    {
      name: 'stat3Label_en',
      title: 'Stat 3 - Label (EN)',
      type: 'string',
      group: 'results',
    },
  ],
  preview: {
    select: {
      title: 'previewTitle_fr',
      subtitle: 'previewLieu_fr',
      media: 'previewImage',
    },
    prepare: ({ title, subtitle, media }) => ({
      title: title || 'Sans titre',
      subtitle,
      media,
    }),
  },
})
